baseURL = 'https://rbrincke.github.io'

title = "Don't take my word for it, but..."
theme = "LoveIt"

languageCode = 'en-us'
languageName = "English"

[author]
  name = "Robert ten Brincke"

[params]
  title = "Don't take my word for it, but..."
  description = "Don't take my word for it, but..."

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Don't take my word for it, but..."

  [params.social]
    GitHub = 'rbrincke'
    Twitter = 'rhwtenbrincke'

  [params.footer]
    enable = false

  [params.home]
    [params.home.profile]
      enable = true
      title = ""
      subtitle = ""

  [params.app]
    title = "Don't take my word for it, but..."

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

[markup]
  [markup.highlight]
    noClasses = false

